#
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#

name: OpenWRT-X86

on:
  #repository_dispatch:
  workflow_dispatch:
    #inputs:
      #ssh:
        #description: 'SSH connection to Actions'
        #required: false
        #default: 'false'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: config/X86.config
  DIY_P1_SH: bash/diy_script01.sh
  DIY_P2_SH: bash/diy_script02.sh
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  RECENT_LASTEST: 15
  TZ: Asia/Shanghai

permissions: write-all

jobs:
  build_openwrt:
    name: Build X86 Firmware
    runs-on: ubuntu-latest
    steps:
      - name: 初始化环境 #Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install $(curl -fsSL https://github.com/Joshua-DinG/openwrt/raw/main/depends-ubuntu)
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "$TZ"

      - name: 检查 OpenWrt #Checkout OpenWRT
        uses: actions/checkout@v3

      - name: 克隆 LEDE #Clone LEDE Code
        run: |
          git clone --depth=1 --single-branch $REPO_URL

      - name: 更新插件 #Update Plugins
        run: |
          chmod +x $DIY_P1_SH
          cd ./lede       
          $GITHUB_WORKSPACE/$DIY_P1_SH 

      - name: 更新并安装软件包 Feeds #Update Feeds
        run: |
          cd ./lede

          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Custom Settings
        run: |
          if [ -e "$CONFIG_FILE" ]; then
            mv "$CONFIG_FILE" lede/.config
          fi
          chmod +x "$DIY_P2_SH"
          cd lede
          "$GITHUB_WORKSPACE/$DIY_P2_SH"


          make defconfig
          ls -lA
      - name: 下载软件包 #Download Packages
        run: |
          cd ./lede

          make download -j16
          cat .config
      - name: 编译固件 #Compile Firmware
        run: |
          cd ./lede

          make -j$(nproc) || make -j1 V=s

          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./build_dir
          echo "======================="
          du -h --max-depth=1 ./bin
          echo "======================="

      - name: 打包固件 #Package Firmware
        run: |
          export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

          #cd ./lede
          #cp -rf $(find ./bin/targets/ -type f -name '*x86*.*') ./bin/targets/
          #cp -rf ./.config ./bin/targets/config.txt
          tree
          #cd ./bin/targets
          #zip -pmq X86_Firmware_$BUILD_DATE.zip *.*

      - name: Release Firmware
        uses: softprops/action-gh-release@v1
        with:
          tag_name: X86_Firmware_${{env.BUILD_DATE}}
          files: ./lede/bin/targets/*/*/*.*
          body: |
            OpenWrt X86固件 ${{ env.DEVICE_NAME }}
            * 固件信息
            Default IP: 192.168.10.1
            Default username: root
            Default password: password

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 3
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3
