#
# <https://github.com/KFERMercer/OpenWrt-CI>
#
# Copyright (C) 2019 P3TERX
#
# Copyright (C) 2020 KFERMercer
#

name: OpenWRT-X86

on:
  #repository_dispatch:
  workflow_dispatch:
    #inputs:
      #ssh:
        #description: 'SSH connection to Actions'
        #required: false
        #default: 'false'

  push:
    branches: [main]

permissions: write-all

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: config/X86.config
  DIY_P1_SH: bash/diy_script01.sh
  DIY_P2_SH: bash/diy_script02.sh
  COMMIT_LOG_NUM: 1
  RELEASE_TAG: X86
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  UPLOAD_RELEASE: true
  SERVERCHAN_SCKEY: true
  TZ: Asia/Shanghai

jobs:
  build_openwrt:
    name: Build X86 Firmware
    runs-on: ubuntu-latest
    steps:
      - name: 检查准备 #Checkout OpenWRT
        uses: actions/checkout@v2.4.2

      - name: 初始化环境 #Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android /opt/ghc
          sudo -E apt-mark hold grub-efi-amd64-signed
          sudo -E apt update
          sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
          sudo -E apt -y full-upgrade
          sudo -E apt -y install $(curl -fsSL https://github.com/Joshua-DinG/openwrt/raw/main/depends-ubuntu)
          sudo -E systemctl daemon-reload
          sudo -E apt -y autoremove --purge
          sudo -E apt clean
          sudo -E timedatectl set-timezone "$TZ"
          export BUILD_DATE=$(TZ=UTC-8 date +"%y-%m-%d_%H-%M-%S")
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV

      - name: Clone LEDE Code
        run: |
          git clone --depth=1 --single-branch $REPO_URL.git

      - name: script1自定义设置 #Load custom feeds
        run: |
          [ -e $FEEDS_CONF ] && mv $FEEDS_CONF lede/feeds.conf.default
          chmod +x $DIY_P1_SH
          cd ./lede
          $GITHUB_WORKSPACE/$DIY_P1_SH

      - name: 更新源 #Update feeds
        run: cd ./lede && ./scripts/feeds update -a

      - name: 安装源 #Install feeds
        run: cd ./lede && ./scripts/feeds install -a

      - name: script2自定义设置 #Load custom configuration
        run: |
          [ -e files ] && mv files lede/files
          rm -rf ./tmp && rm -rf ./.config*
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE lede/.config
          chmod +x $DIY_P2_SH
          cd ./lede
          $GITHUB_WORKSPACE/$DIY_P2_SH

      - name: Download Packages
        run: |
          cd ./lede
          make download -j16
      - name: Compile Firmware
        run: |
          cd ./lede
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./build_dir
          echo "======================="
          du -h --max-depth=1 ./bin
          echo "======================="
      - name: Package Firmware
        run: |
          cd ./lede
          cp -rf $(find ./bin/targets/ -type f -name '*.img.gz') ./bin/targets/
          cp -rf ./.config ./bin/targets/config.txt
          cd ./bin/targets
          zip -pmq R4S_Firmware_$BUILD_DATE.zip *.*
      - name: Release Firmware
        uses: softprops/action-gh-release@v1
        with:
          tag_name: R4S_Firmware_${{env.BUILD_DATE}}
          files: ./lede/bin/targets/*.zip
          body: |
            This is OpenWrt firmware for ${{ env.DEVICE_NAME }}
            * Firmware information
            Default IP: 192.168.10.1
            Default username: root
            Default password: password
            Default WIFI name: OpenWrt
            Default WIFI password: none
            [WETRANSFER](${{ env.WET_URL }})

      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@v0.2.1
        with:
          keep_latest: 3
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          retain_days: 1
          keep_minimum_runs: 3

