#=================================================
# OpenWRT-CI Workflows for Build OpenWRT firmware
# 
#=================================================

name: Build_OpenWRT

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: config/X86.config
  DIY_P1_SH: bash/diy_script01.sh
  DIY_P2_SH: bash/diy_script02.sh
  COMMIT_LOG_NUM: 1
  DEVICE_NAME: X86
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  UPLOAD_COWTRANSFER: false
  UPLOAD_WETRANSFER: false
  RECENT_LASTEST: 15
  TZ: Asia/Shanghai

permissions: write-all

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout OpenWRT
      uses: actions/checkout@v3 

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi `docker images -q`
        sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
        sudo -E apt-mark hold grub-efi-amd64-signed
        sudo -E apt update
        sudo -E apt -y purge azure-cli* docker* ghc* zulu* llvm* firefox google* dotnet* powershell* openjdk* mysql* php* mongodb* dotnet* moby* snap*
        sudo -E apt -y full-upgrade
        sudo -E apt -y install $(curl -fsSL https://github.com/Joshua-DinG/openwrt/raw/main/depends-ubuntu)
        sudo -E systemctl daemon-reload
        sudo -E apt -y autoremove --purge
        sudo -E apt clean
        sudo -E timedatectl set-timezone "$TZ"
        export BUILD_DATE=$(TZ=UTC-8 date +"%y.%m.%d_%H.%M.%S")
        echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
        echo "DEVICE_NAME=$DEVICE_NAME" >> $GITHUB_ENV

    - name: Clone LEDE Code
      run: |
        git clone --depth=1 --single-branch $REPO_URL
        chmod +x $DIY_P1_SH; cd ./lede; $GITHUB_WORKSPACE/$DIY_P1_SH
        tree 
    - name: Update Feeds01
      run:  |
        cd ./lede && ./scripts/feeds update -a && ./scripts/feeds install -a

    - name: Update Plugins
      run: |
        chmod +x $DIY_P2_SH; cd ./lede; $GITHUB_WORKSPACE/$DIY_P2_SH

    - name: Custom Settings
      run: |
        cd ./lede && rm -rf ./tmp && rm -rf ./.config*
        cat $GITHUB_WORKSPACE/config/X86.config > .config
        make defconfig && ls -lA && cat .config

    - name: Download Packages
      run: cd ./lede && make -j16 download

    - name: Compile Firmware
      run: |
        cd ./lede
        make -j$(nproc) || make -j1 V=s
        echo "======================="
        df -h
        echo "======================="
        du -h --max-depth=1 ./build_dir
        echo "======================="
        du -h --max-depth=1 ./bin
        echo "======================="        

    - name: Release Firmware
      uses: softprops/action-gh-release@v1
      with:
        tag_name: X86_Firmware_${{env.BUILD_DATE}}
        files: ./lede/bin/targets/*/*/*.*
        body: |
          OpenWrt X86固件 ${{ env.DEVICE_NAME }}
          * 固件信息
          Default IP: 192.168.2.88
          Default username: root
          Default password: 

    - name: Delete Old Releases
      uses: dev-drprasad/delete-older-releases@v0.2.1
      with:
        keep_latest: 3
        delete_tags: true

    - name: Delete Old Workflows
      uses: Mattraks/delete-workflow-runs@v2
      with:
        retain_days: 1
        keep_minimum_runs: 3           
